# 공통
spring:
  thymeleaf:
    cache: false

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul   # ✅ Hibernate가 DB ↔ Java 변환할 때 KST 사용

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid, profile, email

  jackson:
    time-zone: Asia/Seoul   # ✅ JSON 직렬화/역직렬화도 KST로 맞춤

server:
  port: ${PORT:8080}

logging:
  level:
    org.thymeleaf: DEBUG
    org.springframework.security: DEBUG

---
spring:
  profiles:
    active: local   # 기본 실행은 로컬




